version: '3'

services:
    app:
        build: 
            context: node
        container_name: nodeapp     
        image: gbofullcycle/node-desafio-fc
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh   
        command: [ "node", "index.js" ]
        networks: 
            - desafiodois-network
        volumes: 
            - ./node:/usr/src/app
        tty: true
        ports: 
            - "3000:3000"
        depends_on: 
            - db
    nginx:
        build: 
            context: nginx
        container_name: nginx
        image: gbofullcycle/nginx-desafio-fc
        restart: always
        networks: 
            - desafiodois-network
        ports: 
            - "8080:80"
    db:
        build: 
            context: .
        image: gbofullcycle/mysql-desafio-fc        
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./dumb/dumb.sql:/docker-entrypoint-initdb.d/1.sql
            - ./mysql:/var/lib/mysql            
        networks: 
            - desafiodois-network

networks: 
    desafiodois-network:
        driver: bridge
